name: Checks

on: [push] # trigger 역할

jobs: # 실행 workflow 관리
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login in to Docker Hub
        uses: docker/login-action@v1 # actions 에서 docker container 로 접근하기 위한 패키지 설치
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint(Flake8)
        run: docker-compose run --rm app sh -c "flake8"